### ISSUE TITLE
Pretrain model

### ISSUE THREAD

**Issue by Tian-one** [WarranWeng/EBFI-BE#1]
I am really interested in your work! Could you please release your pretrain model?

**Comment by WarranWeng** [comment]
Will be updated in a week.

**Comment by Tian-one** [comment]
> Will be updated in a week.

Thanks for your released model! Can you please provide the pre-trained model on the GoPro dataset? It seems that the currently published model is trained on the Realsharp-DAVIS dataset. Thanks!
